### ISSUE TITLE
svd vs eig

### ISSUE THREAD

**Issue by Vkomini** [dimkastan/PyTorch-Spectral-clustering#1]
At your file demo.py do we have to do torch.svd of the distance matrix or simple torch.eig?
I guess torch.svd would not give the same result as torch.eig for clustering on the spectral space!

**Comment by dimkastan** [comment]
Hi, thanks for the comment.
I think that in this example I do SVD on a distance matrix but I will check it.
As I am not actively maintaining this repo (but I plan to do an update soon), 
please provide some extra pointers (references etc.) that would help in this direction.

**Comment by Vkomini** [comment]
torch.svd would recompute both Gram and Covariance matrix on the similarity matrix and then compute the eigenvectors of these respective matrices using torch.eig.
Using torch.eig alone in the similarity matrix would provide the correct spectral.
